### ISSUE TITLE
ReferenceError: window is not defined when using esm with nodejs

### ISSUE THREAD

**Issue by Jontem** [nats-io/jwt.js#15]
Hi!

I'm getting this error when using es modules with node and calling the methods `createUser` or `createAccount`

```
 file:///path_to_my_project/node_modules/nats-jwt/esm/jwt.js:680
     window.crypto.getRandomValues(b);

 ReferenceError: window is not defined
     at Object.randomBytes (file:///path_to_my_project/node_modules/nats-jwt/esm/jwt.js:680:5)
     at createPair (file:///path_to_my_project/node_modules/nats-jwt/esm/jwt.js:2570:40)
     at createUser (file:///path_to_my_project/node_modules/nats-jwt/esm/jwt.js:2352:12)
```

This is the function in the bundled `esm/jwt.js`
```
function randomBytes(n) {
    let b = ByteArray(n);
    window.crypto.getRandomValues(b);
    return b;
}
```

**Comment by aricart** [comment]
The esm module is expecting a browser-compatible environment - if you use require it will unwedge you for now. I need to figure out how to inject that dependency from the esm side to the nkey library.

**Comment by aricart** [comment]
I have been working on a small overhaul to the nkeys.js library which converts the standard tweetnacl lib to esm, so I thought I tackle this use case. However this is actually more difficult than should be. While  I can easily patch randomBytes(), other crypto.subtle apis for generating hashes are more difficult, so I am not going to undertake that level of compatibility. If you can shim crypto/crypto subtle you'll be able to run the library no problem. Otherwise you'll have to use CJS version of the functionality.

**Comment by Jontem** [comment]
F.Y.I. I tried `0.0.3` and this error is now gone.
